on: [push, pull_request]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Wasm-Pack
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

      - name: Build WebAssembly
        run: wasm-pack build

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: 12
      - run: cd www
      - run: npm install
      - run: npm run build

      - name: Deploy
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: gh_pages
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_REPO_TOKEN }}
